config/routes.rb
Rails.application.routes.draw do
  root "games#new"
  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
# app/models/card.rb
class Card < ApplicationRecord
    enum suit: [:hearts, :diamonds, :clubs, :spades]
    enum rank: [:ace, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :jack, :queen, :king]
  
    def value
      if rank == "ace"
        11
      elsif ["jack", "queen", "king"].include?(rank)
        10
      else
        rank.to_i
      end
    end
  end
  

app/models/dealer.rb
# app/models/dealer.rb
class Dealer < ApplicationRecord
    has_many :cards, as: :cardable
    belongs_to :table
  
    def total_points
      total = cards.sum(&:value)
      aces_count = cards.count(&:ace?)
      while total > 21 && aces_count > 0
        total -= 10
        aces_count -= 1
      end
      total
    end
  
    def deal_to_self
      while total_points < 17
        deal_card(self)
      end
    end
  
    def deal_card(cardable)
      card = table.deck.cards.pop
      card.update(cardable: cardable)
    end
  end
  

app/models/deck.rb
# app/models/deck.rb
class Deck < ApplicationRecord
    has_many :cards
  
    def build_deck
      Card.suits.keys.each do |suit|
        Card.ranks.keys.each do |rank|
          cards.build(suit: suit, rank: rank)
        end
      end
      cards.shuffle!
    end
  end
  

app/models/game.rb
# game.rb
class Game < ApplicationRecord
    serialize :player_cards, Array
    serialize :dealer_cards, Array
    def deck=(deck)
        @deck = deck
      end
    def initialize_deck
      @deck = Deck.new
      @deck.build_deck
    end
  
    def deal_initial_cards
      initialize_deck
  
      self.player_cards = []
      self.dealer_cards = []
  
      2.times do
        player_cards << deck.draw_card
        dealer_cards << deck.draw_card
      end
  
      save
    end
  
    def player_total_points
      calculate_total_points(player_cards)
    end
  
    def dealer_total_points
      calculate_total_points(dealer_cards)
    end
  
    def player_turn?
      player_total_points < 21 && !game_over?
    end
  
    def game_over?
      player_total_points >= 21 || dealer_total_points >= 21
    end
  
    def player_won?
      player_total_points <= 21 && (dealer_total_points > 21 || player_total_points > dealer_total_points)
    end
  
    def dealer_won?
      dealer_total_points <= 21 && (player_total_points > 21 || dealer_total_points > player_total_points)
    end
  
    private
  
    def calculate_total_points(cards)
      total = 0
      aces_count = 0
  
      cards.each do |card|
        total += card.value
        aces_count += 1 if card.rank == "ace"
      end
  
      while total > 21 && aces_count > 0
        total -= 10
        aces_count -= 1
      end
  
      total
    end
  end
  

app/models/game_decision.rb
# app/models/game_decision.rb
class GameDecision < ApplicationRecord
    belongs_to :player
  end
  

app/models/player.rb
# app/models/player.rb
class Player < ApplicationRecord
    has_many :game_decisions
    has_many :cards, through: :game_decisions
    belongs_to :table
  
    def total_points
      total = cards.sum(&:value)
      aces_count = cards.count(&:ace?)
      while total > 21 && aces_count > 0
        total -= 10
        aces_count -= 1
      end
      total
    end
  end
  

app/models/table.rb
# app/models/table.rb
class Table < ApplicationRecord
    has_one :dealer
    has_many :players
    has_many :game_decisions, through: :players
  
    def deck
      @deck ||= Deck.new
    end
  
    def deal_initial_cards
      2.times do
        players.each do |player|
          deal_card(player)
        end
        deal_card(dealer)
      end
    end
  
    def deal_card(player)
      card = deck.cards.pop
      player.cards << card
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# app/controllers/games_controller.rb
class GamesController < ApplicationController
    def new
      @game = Game.new
    end
  
    # app/controllers/games_controller.rb

    def create
        @game = Game.new(game_params)
        @deck = Deck.new # デッキオブジェクトを作成

        @game.deck = @deck # @gameオブジェクトのdeck属性にデッキオブジェクトを代入        
        if @game.save
        @game.deal_initial_cards # カードを配る処理を追加
    
        redirect_to game_path(@game)
        else
        render :new
        end
    end

    def show
      @game = Game.find(params[:id])
    end
  
    def hit
      @game = Game.find(params[:id])
      @game.player_hit
      redirect_to game_path(@game)
    end
  
    def surrender
      @game = Game.find(params[:id])
      @game.player_surrender
      redirect_to game_path(@game)
    end
  
    private
  
    def game_params
      # パラメータの設定
      params.require(:game).permit(:player_name)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<!-- app/views/games/new.html.erb -->
<h1>New Game</h1>

<%= form_with(model: @game, url: games_path, method: :post) do |form| %>
  <%= form.label :player_name, "Player Name" %>
  <%= form.text_field :player_name %>
  <%= form.submit "Start Game" %>
<% end %>

app/views/games/show.html.erb
<!-- app/views/games/show.html.erb -->
<h1>Blackjack Game</h1>

<h2>Player: <%= @game.player_name %></h2>
<h3>Player Hand:</h3>
<ul>
  <% @game.player_cards.each do |card| %>
    <li><%= card.rank %> of <%= card.suit %></li>
  <% end %>
</ul>
<p>Total Points: <%= @game.player_total_points %></p>

<h3>Dealer Hand:</h3>
<ul>
  <% @game.dealer_cards.each do |card| %>
    <li><%= card.rank %> of <%= card.suit %></li>
  <% end %>
</ul>
<p>Total Points: <%= @game.dealer_total_points %></p>

<% if @game.game_over? %>
  <% if @game.player_won? %>
    <p>Congratulations! You won!</p>
  <% elsif @game.dealer_won? %>
    <p>Sorry, you lost. Dealer won.</p>
  <% else %>
    <p>It's a tie!</p>
  <% end %>
<% else %>
  <% if @game.player_turn? %>
    <%= form_with(url: hit_game_path(@game), method: :post) do |form| %>
      <%= form.submit "Hit" %>
    <% end %>
    <%= form_with(url: surrender_game_path(@game), method: :post) do |form| %>
      <%= form.submit "Surrender" %>
    <% end %>
  <% else %>
    <p>Dealer's turn...</p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blackjack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>